const refs = {
  body: document.querySelector('.body'),
  searchForm: document.querySelector('#search-form'),
  notFoundNotice: document.querySelector('.js-search-error'),
  allFoundFilms: document.querySelector('.js-search-all_found'),
  gallery: document.querySelector('.js-gallery'),
  openModal: document.querySelector('.js-modal-open'),
  submitBtn: document.querySelector('.js-submit-form'),
  inputForm: document.querySelector('.js-input-form'),
  homeBtn: document.querySelector('.js-home-button'),
  logoBtn: document.querySelector('.js-logo-button'),
  backdrop: document.querySelector('.js-backdrop'),
  modalContent: document.querySelector('.backdrop-content'),
  modal: document.querySelector('.modal'),
  modalBox: document.querySelector('[data-modal]'),
  header: document.querySelector('.header'),
  paginationBox: document.querySelector('.js-pagination-box'),
  pagingList: document.querySelector('.js-pagination-box_pages'),
  footer: document.querySelector('.footer'),
  main: document.querySelector('main'),
  libraryBtnRef: document.querySelector('.js-my-library-button'),
  watchedBtnRef: document.querySelector('.watched-show-btn'),
  queueBtnRef: document.querySelector('.queue-show-btn'),
  headerRef: document.querySelector('.header'),
  spinnerRef: document.querySelector('#load'),
  overlayRef: document.querySelector('.backdrop_overlay'),
  themeSwitchRef: document.querySelector('#theme-switch-toggle'),
};
export default refs;
